export interface NameEntry {
  name: string;
  origin: string;
  meaning: string;
  curiosity: string;
  aliases?: string[];
}

export const NAMES_DB: NameEntry[] = [
  // === 50 nomes femininos mais populares ===
  { name: "Maria", origin: "Hebraica", meaning: "A amada de Deus, a cheia de graça", curiosity: "O nome mais registrado no Brasil por mais de 80 anos consecutivos." },
  { name: "Helena", origin: "Grega", meaning: "A resplandecente, a que brilha", curiosity: "Em grego, vem de 'helene' (tocha). Helena de Tróia foi a mais bela mulher do mundo na mitologia." },
  { name: "Alice", origin: "Germânica", meaning: "De nobre linhagem, nobre", curiosity: "Popularizado por Lewis Carroll em 'Alice no País das Maravilhas' (1865)." },
  { name: "Laura", origin: "Latina", meaning: "A laureada, vencedora", curiosity: "Na Roma antiga, a coroa de louros simbolizava vitória e sabedoria." },
  { name: "Manuela", origin: "Hebraica", meaning: "Deus está conosco", curiosity: "É a forma feminina de Manuel, uma variante de Emmanuel." },
  { name: "Valentina", origin: "Latina", meaning: "A forte, a valente", curiosity: "Santo Valentino é o padroeiro dos namorados, festejado em 14 de fevereiro." },
  { name: "Sophia", origin: "Grega", meaning: "Sabedoria, inteligência", curiosity: "Hagia Sophia em Istambul é uma das mais famosas basílicas do mundo." },
  { name: "Isabella", origin: "Hebraica", meaning: "Consagrada a Deus, promessa de Deus", curiosity: "Isabel I da Inglaterra, conhecida como 'Rainha Virgem', governou por 45 anos." },
  { name: "Heloisa", origin: "Germânica", meaning: "Guerreira famosa, saudável", curiosity: "A tragédia de Heloisa e Abelardo no século XII é uma das histórias de amor mais conhecidas." },
  { name: "Lara", origin: "Grega", meaning: "A alegre, a brilhante", curiosity: "Na mitologia, Lara era uma ninfa romana que revelou segredos dos deuses." },
  { name: "Julia", origin: "Latina", meaning: "Jovem, cheia de juventude", curiosity: "Júlia era uma das famílias patrícias mais importantes de Roma, incluindo Júlio César." },
  { name: "Lorena", origin: "Latina", meaning: "A laureada, natural da Lorena", curiosity: "Lorena é uma região histórica no nordeste da França, fronteira com Alemanha." },
  { name: "Livia", origin: "Latina", meaning: "A oliva, a pacífica", curiosity: "Lívia Drusa Augusta foi esposa do imperador romano Augusto e imperatriz-consorte." },
  { name: "Cecilia", origin: "Latina", meaning: "A cega, a modesta", curiosity: "Santa Cecília é padroeira da música e dos músicos." },
  { name: "Elisa", origin: "Hebraica", meaning: "Deus é minha salvação", curiosity: "Elisa é uma forma curta de Isabel/Elizabeth, muito usada em Portugal e Brasil." },
  { name: "Marina", origin: "Latina", meaning: "Do mar, marinha", curiosity: "Santa Marina de Antioquia é uma santa cristã que foi confundida com um homem durante anos." },
  { name: "Eloa", origin: "Hebraica", meaning: "Deus é meu juramento", curiosity: "Eloa é uma variação brasileira de Eloise, com sonoridade suave e moderna." },
  { name: "Melissa", origin: "Grega", meaning: "Abelha", curiosity: "Na mitologia grega, Melissa foi a ninfa que descobriu o mel e ensinou os homens a criar abelhas." },
  { name: "Sarah", origin: "Hebraica", meaning: "Princesa, nobre", curiosity: "Sarah era esposa de Abraão na Bíblia e mãe de Isaque aos 90 anos." },
  { name: "Isabel", origin: "Hebraica", meaning: "Deus é juramento, consagrada a Deus", curiosity: "Isabel, a Católica, financiou a viagem de Cristóvão Colombo à América." },
  { name: "Yasmin", origin: "Persa/Árabe", meaning: "Jasmim, flor perfumada", curiosity: "O jasmim é uma flor sagrada em muitas culturas, símbolo de pureza e amor." },
  { name: "Antonella", origin: "Latina", meaning: "A valiosa, digna de louvor", curiosity: "Diminutivo italiano de Antonia, muito popular na Argentina e Brasil." },
  { name: "Raquel", origin: "Hebraica", meaning: "A ovelha, a inocente", curiosity: "Raquel era esposa de Jacó na Bíblia e mãe de José e Benjamim." },
  { name: "Esther", origin: "Persa", meaning: "Estrela, a escondida", curiosity: "Rainha Ester salvou o povo judeu da perseguição no Império Persa, conforme o Livro de Ester." },
  { name: "Olivia", origin: "Latina", meaning: "A oliveira, a pacífica", curiosity: "A oliveira é um símbolo de paz desde a Antiguidade, presente no arca de Noé." },
  { name: "Larissa", origin: "Grega", meaning: "A citadina, a alegre", curiosity: "Larissa é uma cidade antiga na Tessália, Grécia, e também um nome de ninfa." },
  { name: "Emily", origin: "Latina", meaning: "A rival, a que compete", curiosity: "Emily Dickinson é uma das mais importantes poetas estadunidenses da história.", aliases: ["Emilly", "Emyly", "Emille"] },
  { name: "Aurora", origin: "Latina", meaning: "A amanhecer, a alvorada", curiosity: "Aurora é a deusa romana da aurora, equivalente à Eos na mitologia grega." },
  { name: "Aline", origin: "Germânica", meaning: "Nobre, de linhagem nobre", curiosity: "Aline é uma forma curta de Adeline, muito popular na França e Brasil." },
  { name: "Agatha", origin: "Grega", meaning: "A boa, a virtuosa", curiosity: "Santa Ágata de Catânia é uma das sete santas virgens mais reverenciadas da Igreja." },
  { name: "Rebeca", origin: "Hebraica", meaning: "Laço, amarração", curiosity: "Rebeca foi esposa de Isaque e mãe de Esaú e Jacó na Bíblia." },
  { name: "Fernanda", origin: "Germânica", meaning: "A corajosa, a viajante audaz", curiosity: "Forma feminina de Fernando, de origem germânica 'frith' (paz) + 'nanth' (audácia)." },
  { name: "Amanda", origin: "Latina", meaning: "Digna de amor, amável", curiosity: "Popularizado nos anos 1980 no Brasil, Amanda era um nome comum na Roma antiga." },
  { name: "Bianca", origin: "Italiana", meaning: "Branca, pura, luminosa", curiosity: "Bianca foi uma personagem célebre em Shakespeare, aparecendo em 'Othelo' e 'A Megera Domada'." },
  { name: "Luiza", origin: "Germânica", meaning: "Guerreira gloriosa, famosa", curiosity: "Forma feminina de Luís, vinda de 'Hludwig' (glória + combate)." },
  { name: "Maya", origin: "Hebraica/Grega", meaning: "Água, mãe, grande", curiosity: "Na mitologia grega, Maya é uma das Plêiades e mãe de Hermes. Em hebraico, significa água." },
  { name: "Giovanna", origin: "Hebraica", meaning: "Deus é cheio de graça", curiosity: "Forma italiana de Joana, muito popular no Brasil desde a década de 1990." },
  { name: "Aline", origin: "Germânica", meaning: "Nobre, pequena nobre", curiosity: "Uma forma de Adeline que ganhou popularidade no Brasil nas décadas de 1980 e 1990." },
  { name: "Bruna", origin: "Germânica", meaning: "Morena, de cabelo escuro", curiosity: "De 'brun' (marrom), o nome indica a cor dos cabelos e tornou-se muito popular no Brasil." },
  { name: "Camila", origin: "Latina", meaning: "Jovem servidora, pura", curiosity: "Camila na mitologia romana era uma sacerdotisa virgem guerreira que corria mais rápido que o vento." },
  { name: "Carolina", origin: "Germânica", meaning: "Mulher do povo, livre", curiosity: "De 'Karl' (homem) + 'linda' (suave), o nome foi popularizado por rainhas europeias." },
  { name: "Catarina", origin: "Grega", meaning: "A pura", curiosity: "Santa Catarina de Alexandria, mártir, é uma das santas mais reverenciadas do cristianismo." },
  { name: "Daniela", origin: "Hebraica", meaning: "Deus é meu juiz", curiosity: "Forma feminina de Daniel, que na Bíblia escapou das feras na cova dos leões." },
  { name: "Eduarda", origin: "Anglo-Saxã", meaning: "Guardiã das riquezas", curiosity: "Forma feminina de Eduardo, de 'ead' (riqueza, fortuna) + 'weard' (guardião)." },
  { name: "Gabriela", origin: "Hebraica", meaning: "Deus é minha força", curiosity: "Forma feminina de Gabriel, o arcanjo que anunciou a Maria a vinda de Jesus." },
  { name: "Josefina", origin: "Hebraica", meaning: "Deus multiplicará", curiosity: "Forma feminina de José, de 'Yosef' (acrescentar, multiplicar), um dos nomes bíblicos mais importantes." },
  { name: "Leticia", origin: "Latina", meaning: "Alegria, felicidade", curiosity: "De 'laetitia', o nome significa alegria e foi popularizado por santas romanas." },
  { name: "Natalia", origin: "Latina", meaning: "Natal, nascida no dia de Natal", curiosity: "De 'natalis', popularizado em países de língua espanhola e portuguesa." },
  { name: "Patricia", origin: "Latina", meaning: "Da nobreza, patrícia", curiosity: "Na Roma antiga, patrícios eram membros da aristocracia." },
  { name: "Roberta", origin: "Germânica", meaning: "A gloriosa, a famosa", curiosity: "Forma feminina de Roberto, de 'hrod' (fama) + 'beraht' (brilhante)." },
  { name: "Tatiana", origin: "Latina", meaning: "Da família Tácio, ordenada", curiosity: "Tatiana de Roma foi uma mártir cristã do século III, padroeira de estudantes.", aliases: ["Tatiane", "Tatyane", "Tatiani"] },
  { name: "Vitoria", origin: "Latina", meaning: "A vitoriosa, a vencedora", curiosity: "Vitória é uma deusa romana equivalente à Nike na mitologia grega." },
  // === 50 nomes masculinos mais populares ===
  { name: "Miguel", origin: "Hebraica", meaning: "Quem é como Deus?", curiosity: "Miguel é o arcanjo guerreiro que combateu Satanás no Apocalipse." },
  { name: "Arthur", origin: "Celta", meaning: "Urso, o nobre ursino", curiosity: "Rei Artur é uma das lendas mais famosas da Inglaterra, com a Távola Redonda." },
  { name: "Heitor", origin: "Grega", meaning: "O que retém, o defensor", curiosity: "Heitor foi o maior guerreiro troiano na Guerra de Troia, filho de Priamo." },
  { name: "Theo", origin: "Grega", meaning: "Deus, divino", curiosity: "Theo é um diminutivo moderno de Teodoro, Theobaldo e Teodoro, muito usado no Brasil." },
  { name: "Davi", origin: "Hebraica", meaning: "O amado, o querido", curiosity: "Davi foi o segundo rei de Israel, que derrotou Golias com uma funda e três pedras." },
  { name: "Gabriel", origin: "Hebraica", meaning: "Deus é minha força", curiosity: "Gabriel é o arcanjo que anunciou a Maria o nascimento de Jesus e a Maomé a revelação." },
  { name: "Bernardo", origin: "Germânica", meaning: "Urso forte, corajoso como urso", curiosity: "São Bernardo de Claraval fundou mosteiros e inspirou a ordem cisterciense." },
  { name: "Samuel", origin: "Hebraica", meaning: "Deus ouviu, ouvido por Deus", curiosity: "Samuel foi o último juiz de Israel e ungiu Saul e Davi como reis." },
  { name: "Pedro", origin: "Grega", meaning: "Pedra, rocha", curiosity: "Pedro foi o primeiro papa da Igreja Católica, a quem Jesus disse: 'Tu és Pedro, e sobre esta pedra...'." },
  { name: "Lucas", origin: "Grega", meaning: "Luminoso, reluzente", curiosity: "Lucas foi um dos evangelistas do Novo Testamento, considerado médico e pintor." },
  { name: "Benjamin", origin: "Hebraica", meaning: "Filho da mão direita, filho da felicidade", curiosity: "Benjamim era o filho mais novo de Jacó e Raquel, fundador da tribo de Benjamim." },
  { name: "Matheus", origin: "Hebraica", meaning: "Dom de Deus, presente do Senhor", curiosity: "Mateus foi um dos doze apóstolos, anteriormente cobrador de impostos." },
  { name: "Gustavo", origin: "Germânica", meaning: "O bastão dos godos, protegido", curiosity: "De 'Gautstafr', refere-se ao bastão de comando dos godos, povo germânico antigo." },
  { name: "Nicolas", origin: "Grega", meaning: "Vitoria do povo", curiosity: "São Nicolau, patrono de crianças, inspirou a figura do Papai Noel ocidental." },
  { name: "Noah", origin: "Hebraica", meaning: "Descanso, repouso, conforto", curiosity: "Noé construiu a arca e salvou sua família e os animais do Dilúvio Universal." },
  { name: "Henrique", origin: "Germânica", meaning: "Senhor da casa, governante do lar", curiosity: "De 'Heinrich', o nome foi usado por oito reis da Inglaterra e reis da Alemanha." },
  { name: "Guilherme", origin: "Germânica", meaning: "Protetor determinado, escudo resoluto", curiosity: "Guilherme, o Conquistador, invadiu a Inglaterra em 1066 e mudou a história europeia." },
  { name: "Rafael", origin: "Hebraica", meaning: "Deus cura, curado por Deus", curiosity: "Rafael é o arcanjo da cura na Bíblia, que guiou Tobias em sua jornada." },
  { name: "Daniel", origin: "Hebraica", meaning: "Deus é meu juiz", curiosity: "Daniel na Bíblia foi lançado na cova dos leões e sobreviveu por sua fé." },
  { name: "Vitor", origin: "Latina", meaning: "O vitorioso, o vencedor", curiosity: "Vitor foi um nome comum entre os gladiadores romanos e imperadores." },
  { name: "Leonardo", origin: "Germânica", meaning: "Leão forte, corajoso como leão", curiosity: "Leonardo da Vinci foi um dos gênios mais completos da história da humanidade." },
  { name: "Enzo", origin: "Germânica", meaning: "Senhor da casa, governante", curiosity: "Diminutivo de nomes como Lorenzo, Vincenzo, e Enzo, muito popular na Itália e Brasil." },
  { name: "Bryan", origin: "Celta", meaning: "Nobre, forte, virtuoso", curiosity: "De Brian Boru, o último grande rei da Irlanda, que unificou a ilha no século XI." },
  { name: "Eduardo", origin: "Anglo-Saxã", meaning: "Guardião das riquezas", curiosity: "Oito reis da Inglaterra se chamaram Eduardo, incluindo Eduardo, o Confessor." },
  { name: "Rodrigo", origin: "Germânica", meaning: "Famoso governante, glória do líder", curiosity: "Rodrigo Díaz de Vivar, o Cid Campeador, é o maior herói da literatura espanhola." },
  { name: "Antonio", origin: "Latina", meaning: "Digno de louvor, de valor inestimável", curiosity: "De Antonius, uma família romana. Santo Antônio de Pádua é o santo mais popular do Brasil." },
  { name: "Caua", origin: "Tupi-Guarani", meaning: "Gavião", curiosity: "Um dos nomes indígenas brasileiros mais registrados, simboliza força e liberdade." },
  { name: "Felipe", origin: "Grega", meaning: "O amigo dos cavalos, amante dos cavalos", curiosity: "De 'philos' (amigo) + 'hippos' (cavalo). Felipe II foi pai de Alexandre, o Grande." },
  { name: "Joao", origin: "Hebraica", meaning: "Deus é cheio de graça, Deus é misericordioso", curiosity: "João é o nome mais comum em Portugal e um dos mais populares no Brasil." },
  { name: "Vicente", origin: "Latina", meaning: "O vitorioso", curiosity: "São Vicente de Paulo fundou ordens religiosas dedicadas a ajudar os pobres." },
  { name: "Francisco", origin: "Latina", meaning: "O francês, o livre", curiosity: "São Francisco de Assis fundou a ordem franciscana e é padroeiro da Itália e dos animais." },
  { name: "Caleb", origin: "Hebraica", meaning: "Corajoso, fiel, leal ao coração", curiosity: "Caleb foi um dos dois espias que voltaram com boas notícias sobre Canaã na Bíblia." },
  { name: "Benicio", origin: "Latina", meaning: "Bem-aventurado, abençoado", curiosity: "De 'benedictus', popularizado no Brasil. Benício é uma forma moderna e elegante." },
  { name: "Bruno", origin: "Germânica", meaning: "Moreno, escudo, proteção", curiosity: "De 'brun' (marrom), Bruno de Colônia foi um filósofo místico queimado na Inquisição." },
  { name: "Caio", origin: "Latina", meaning: "Alegre, feliz, o que se regozija", curiosity: "Caio era um nome romano comum, associado às famílias patrícias." },
  { name: "Diego", origin: "Hebraica", meaning: "Sucessor, ensinado por Deus", curiosity: "De Santiago, Diego é uma forma popular hispânica. São Diego de Alcalá é santo espanhol." },
  { name: "Emanuel", origin: "Hebraica", meaning: "Deus está conosco", curiosity: "Emanuel é uma profecia do Antigo Testamento sobre o Messias, citada no Evangelho de Mateus.", aliases: ["Emanoel", "Imanuel"] },
  { name: "Erick", origin: "Nórdica", meaning: "Rei eterno, senhor supremo", curiosity: "De 'Eirik', Erik, o Vermelho, descobriu a Groenlândia e Erik, o São, foi o primeiro rei cristão da Noruega." },
  { name: "Fabio", origin: "Latina", meaning: "Favorecido, cultivador de feijões", curiosity: "Na Roma antiga, Fabio era uma família patrícia famosa pela tática de 'guerra de atrito'." },
  { name: "Gael", origin: "Celta", meaning: "Generoso, líder, celta", curiosity: "Gaélico refere-se aos povos celtas da Irlanda, Escócia e Ilha de Man." },
  { name: "Hugo", origin: "Germânica", meaning: "Inteligente, espírito, mente", curiosity: "De 'hug' (espírito, inteligência), Hugo era um nome comum entre reis e nobres da Europa." },
  { name: "Igor", origin: "Nórdica", meaning: "Guerreiro do arco, arqueiro", curiosity: "De 'Yngvar', Igor é uma forma eslava. O nome ganhou popularidade no Brasil nos anos 1990." },
  { name: "Joaquim", origin: "Hebraica", meaning: "Deus estabelecerá, fundado por Deus", curiosity: "São Joaquim é pai da Virgem Maria na tradição cristã." },
  { name: "Kevin", origin: "Celta", meaning: "Gentil, nobre, querido", curiosity: "De 'Caoimhín', São Kevin de Glendalough é um santo irlandês do século VI." },
  { name: "Lorenzo", origin: "Latina", meaning: "Do Loureiro, laureado", curiosity: "São Lourenço foi um diácono romano martirizado em uma grelha, padroeiro dos cozinheiros." },
  { name: "Marcelo", origin: "Latina", meaning: "Jovem guerreiro, pequeno Marte", curiosity: "De 'Marcus' (Marte), Marcelo era um nome popular entre generais romanos." },
  { name: "Nathan", origin: "Hebraica", meaning: "Ele deu, dom de Deus", curiosity: "Natan foi um profeta na corte de Davi que o repreendeu por seus pecados." },
  { name: "Otavio", origin: "Latina", meaning: "Oitavo, o nascido na oitava posição", curiosity: "Otavio Augusto foi o primeiro imperador romano e fundou o Império Romano." },
  { name: "Pietro", origin: "Grega", meaning: "Pedra, rocha", curiosity: "Forma italiana de Pedro, muito comum no Brasil. Pietro é uma variante elegante." },
  { name: "Raul", origin: "Germânica", meaning: "Conselheiro de lobo, protetor sábio", curiosity: "De 'Radulf', Raul é uma forma francesa do nome. Raul Seixas é um ícone da música brasileira." },
  { name: "Santiago", origin: "Hebraica", meaning: "Sucessor, o que segue", curiosity: "Santiago de Compostela é um dos destinos de peregrinação mais importantes do cristianismo." },
  { name: "Tiago", origin: "Hebraica", meaning: "O que suplanta, o que segue", curiosity: "Tiago, irmão de João, foi um dos apóstolos de Jesus. É uma forma portuguesa de Jacob." },
  { name: "Wesley", origin: "Anglo-Saxã", meaning: "Campo do oeste, claro do oeste", curiosity: "John Wesley fundou o metodismo, uma das maiores denominações cristãs do mundo." },
  // === 50 nomes diversos (mix) ===
  { name: "Noah", origin: "Hebraica", meaning: "Descanso, repouso", curiosity: "Noé construiu a arca que salvou a humanidade e os animais do Dilúvio." },
  { name: "Alice", origin: "Germânica", meaning: "De nobre linhagem", curiosity: "Alice Liddell inspirou Lewis Carroll a escrever 'Alice no País das Maravilhas'." },
  { name: "Sophia", origin: "Grega", meaning: "Sabedoria", curiosity: "Sophia é o nome da personificação da sabedoria em textos gnósticos e cristãos primitivos." },
  { name: "Luna", origin: "Latina", meaning: "A lua", curiosity: "Luna é a deusa romana da Lua, equivalente à Selene na mitologia grega." },
  { name: "Isis", origin: "Egípcia", meaning: "A trona, a poderosa", curiosity: "Ísis era a deusa egípcia da maternidade, magia e fertilidade, esposa de Osíris." },
  { name: "Ayla", origin: "Turca/Hebraica", meaning: "Luz da lua, aureola, halo", curiosity: "Ayla é um nome turco que significa 'luz da lua'. Tornou-se popular após a série 'Ayla'." },
  { name: "Zoe", origin: "Grega", meaning: "Vida", curiosity: "Zoe era um nome comum entre cristãos primitivos, simbolizando a vida eterna." },
  { name: "Chloe", origin: "Grega", meaning: "Broto verde, flor jovem", curiosity: "Chloe era uma epiteto de Deméter, deusa da agricultura na mitologia grega." },
  { name: "Mia", origin: "Hebraica/Italiana", meaning: "Minha, querida, estrela do mar", curiosity: "Mia é uma forma curta de Maria em italiano e de 'mine' (minha) em hebraico." },
  { name: "Eva", origin: "Hebraica", meaning: "A vivente, a que dá vida", curiosity: "Eva foi a primeira mulher na Bíblia, formada da costela de Adão." },
  { name: "Ana", origin: "Hebraica", meaning: "A graciosa, a cheia de graça", curiosity: "Ana era mãe da profetisa Samuel na Bíblia e um dos nomes mais antigos do mundo." },
  { name: "Clara", origin: "Latina", meaning: "Clara, luminosa, brilhante", curiosity: "Santa Clara de Assis fundou a ordem das Clarissas, seguidora de São Francisco." },
  { name: "Lia", origin: "Hebraica", meaning: "A cansada, a cowgirl", curiosity: "Lia foi a primeira esposa de Jacó na Bíblia e mãe de seis filhos." },
  { name: "Rita", origin: "Latina", meaning: "A pérola, a protetora", curiosity: "Santa Rita de Cássia é a padroeira das causas impossíveis e casos difíceis." },
  { name: "Sofia", origin: "Grega", meaning: "Sabedoria", curiosity: "Sofia é uma das sete virtudes cardinais e representa a sabedoria divina." },
  { name: "Victoria", origin: "Latina", meaning: "A vitoriosa", curiosity: "Rainha Vitória governou o Reino Unido por 63 anos, o período mais longo até então." },
  { name: "Amelia", origin: "Germânica", meaning: "Trabalhadora, diligente", curiosity: "Amelia Earhart foi a primeira mulher a atravessar o Atlântico sozinha de avião." },
  { name: "Elisa", origin: "Hebraica", meaning: "Deus é minha salvação", curiosity: "Elisa é uma forma de Elizabeth que ganhou popularidade no Brasil e Portugal." },
  { name: "Jade", origin: "Espanhola", meaning: "Pedra preciosa, flanco", curiosity: "Jade é uma pedra preciosa sagrada na cultura chinesa, símbolo de pureza e sabedoria." },
  { name: "Kiara", origin: "Italiana", meaning: "Clara, luminosa, pequena", curiosity: "Kiara é uma forma de Chiara, nome italiano que significa clara e luminosa." },
  { name: "Nina", origin: "Espanhola/Hebraica", meaning: "Menina, pequena, graciosa", curiosity: "Nina é uma forma carinhosa de menina em espanhol e também nome próprio." },
  { name: "Olivia", origin: "Latina", meaning: "A oliveira", curiosity: "A oliveira é um símbolo de paz desde a Antiguidade e presente na história de Noé." },
  { name: "Stella", origin: "Latina", meaning: "Estrela", curiosity: "Stella é uma forma latina de Estrela, popular na Itália e em países de língua inglesa." },
  { name: "Thalia", origin: "Grega", meaning: "A florida, a que floresce", curiosity: "Tália era uma das Três Graças na mitologia grega, deusa da festividade." },
  { name: "Uriel", origin: "Hebraica", meaning: "Deus é minha luz", curiosity: "Uriel é um arcanjo mencionado em textos apócrifos, associado à sabedoria e à luz." },
  { name: "Yuri", origin: "Russa/Grega", meaning: "Agricultor, trabalhador da terra", curiosity: "Yuri Gagarin foi o primeiro humano a viajar ao espaço, em 1961." },
  { name: "Aaron", origin: "Hebraica", meaning: "O montanhês, o iluminado", curiosity: "Arão era irmão de Moisés e o primeiro sumo sacerdote de Israel." },
  { name: "Adrian", origin: "Latina", meaning: "O de Adriano, o escuro", curiosity: "Adriano era um imperador romano famoso por construir o Muro de Adriano na Inglaterra." },
  { name: "Alexandre", origin: "Grega", meaning: "O defensor do povo, o protetor", curiosity: "Alexandre, o Grande, conquistou o maior império do mundo antigo aos 32 anos." },
  { name: "Andre", origin: "Grega", meaning: "O valente, o corajoso, o masculino", curiosity: "André foi um dos doze apóstolos de Jesus, irmão de Simão Pedro." },
  { name: "Augusto", origin: "Latina", meaning: "O venerável, o majestoso", curiosity: "Augusto foi o primeiro imperador romano e iniciou a Pax Romana, a paz romana." },
  { name: "Bento", origin: "Latina", meaning: "O abençoado, o bem-aventurado", curiosity: "São Bento de Núrsia é padroeiro da Europa e fundador da ordem beneditina." },
  { name: "Cristiano", origin: "Grega", meaning: "O seguidor de Cristo", curiosity: "De 'christianos', Cristiano Ronaldo é um dos jogadores de futebol mais famosos do mundo." },
  { name: "Dante", origin: "Latina", meaning: "O duradouro, o eterno", curiosity: "Dante Alighieri escreveu 'A Divina Comédia', uma das obras mais importantes da literatura." },
  { name: "Elias", origin: "Hebraica", meaning: "O Senhor é meu Deus", curiosity: "Elias foi um profeta hebreu que subiu ao céu em um carro de fogo." },
  { name: "Frederico", origin: "Germânica", meaning: "O rei pacífico, o governante tranquilo", curiosity: "De 'frith' (paz) + 'ric' (rei), Frederico, o Grande, foi rei da Prússia." },
  { name: "Gustavo", origin: "Germânica", meaning: "O bastão dos godos", curiosity: "Gustavo Vasa libertou a Suécia da Dinamarca e se tornou seu primeiro rei." },
  { name: "Heitor", origin: "Grega", meaning: "O defensor, o que retém", curiosity: "Heitor na mitologia grega foi o príncipe troiano e maior guerreiro da cidade." },
  { name: "Ian", origin: "Escocesa", meaning: "Deus é cheio de graça", curiosity: "Ian é uma forma escocesa de João, muito popular no Reino Unido e Brasil." },
  { name: "Jonas", origin: "Hebraica", meaning: "Pomba, mensageiro de paz", curiosity: "Jonas na Bíblia foi engolido por uma grande baleia e depois vomitado em terra firme." },
  { name: "Kaique", origin: "Tupi-Guarani", meaning: "O que desafia, o que vence", curiosity: "Kaique é um nome de origem indígena brasileira que ganhou popularidade nos anos 2000.", aliases: ["Kaike", "Caíque", "Kayque"] },
  { name: "Lucas", origin: "Grega", meaning: "O luminoso", curiosity: "Lucas, o evangelista, é considerado o primeiro iconógrafo cristão da história." },
  { name: "Murilo", origin: "Latina", meaning: "O murado, o protegido", curiosity: "De 'murus' (muro), Murilo é um nome brasileiro que ganhou popularidade nos anos 1990." },
  { name: "Nicolas", origin: "Grega", meaning: "Vitoria do povo", curiosity: "Nicolas Copérnico propôs o heliocentrismo, que o Sol é o centro do sistema solar." },
  { name: "Oscar", origin: "Celta", meaning: "Amigo dos cervos, guerreiro divino", curiosity: "O Prêmio Oscar é o mais prestigiado do cinema mundial, desde 1929." },
  { name: "Paulo", origin: "Latina", meaning: "O pequeno, o modesto", curiosity: "Paulo de Tarso foi o apóstolo que mais escreveu no Novo Testamento." },
  { name: "Renan", origin: "Hebraica", meaning: "O pequeno, o jovem", curiosity: "Renan é um nome de origem hebraica popularizado no Brasil." },
  { name: "Samuel", origin: "Hebraica", meaning: "Deus ouviu", curiosity: "Samuel ungiu Saul e Davi como reis de Israel, o último juiz da nação." },
  { name: "Tomas", origin: "Aramaica", meaning: "O gêmeo", curiosity: "Tomé, o Apóstolo, duvidou da ressurreição de Jesus até tocar suas feridas." },
  { name: "Ulisses", origin: "Grega", meaning: "O que sofre, o odioso", curiosity: "Ulisses (Odisséu) foi o herói grego que criou o Cavalo de Troia." },
  { name: "Vitor", origin: "Latina", meaning: "O vitorioso", curiosity: "Vitor é uma forma curta de Victor, muito popular em países lusófonos." },
  { name: "Wagner", origin: "Germânica", meaning: "O construtor de carroças", curiosity: "Richard Wagner é um dos compositores de ópera mais influentes da história." },
  { name: "Xavier", origin: "Basco", meaning: "O novo lar, o brilhante", curiosity: "São Francisco Xavier foi um dos primeiros missionários jesuítas na Ásia." },
  { name: "Yago", origin: "Hebraica", meaning: "O que suplanta", curiosity: "Yago é uma forma galega e portuguesa de Tiago, nome de um dos apóstolos." },
  { name: "Zion", origin: "Hebraica", meaning: "O monte santo, o lugar mais alto", curiosity: "Zion é uma colina em Jerusalém, símbolo do paraíso terrestre na cultura rastafári." },
  { name: "Abel", origin: "Hebraica", meaning: "Sopro, vapor, respiração", curiosity: "Abel foi o segundo filho de Adão e Eva, morto por seu irmão Caim." },
  { name: "Adriel", origin: "Hebraica", meaning: "Rebanho de Deus, ajuda de Deus", curiosity: "Adriel era um príncipe israelita na Bíblia, mencionado no Livro de Samuel." },
  { name: "Alana", origin: "Celta", meaning: "Belo, harmonioso, pacífico", curiosity: "Alana é uma forma feminina de Alan, um nome celta que significa harmonia." },
  { name: "Bella", origin: "Italiana", meaning: "Bela, linda", curiosity: "Bella é uma forma curta de Isabella, muito popular em países de língua inglesa." },
  { name: "Cecilia", origin: "Latina", meaning: "A cega", curiosity: "Santa Cecília é padroeira da música e dos músicos, martirizada por sua fé." },
  { name: "Diana", origin: "Latina", meaning: "A divina, a celestial", curiosity: "Diana era a deusa romana da lua, caça e fertilidade." },
  { name: "Ester", origin: "Persa", meaning: "Estrela", curiosity: "Rainha Ester salvou os judeus da perseguição de Haman no Império Persa." },
  { name: "Fabiana", origin: "Latina", meaning: "Favorecida, cultivadora", curiosity: "Forma feminina de Fabio, Fabiana é um nome elegante e clássico." },

  // === Leva 5 - nomes masculinos ===
  { name: "André",     origin: "Grega",     meaning: "O homem, o viril, o corajoso",             curiosity: "Nome de um dos doze apóstolos de Jesus, padroeiro da Escócia, Rússia e Grécia." },
  { name: "Alexandre", origin: "Grega",     meaning: "Aquele que protege os homens",             curiosity: "Nome de Alexandre, o Grande, um dos maiores conquistadores da história antiga." },
  { name: "Márcio",    origin: "Latina",    meaning: "Consagrado a Marte, o guerreiro",          curiosity: "Variante de Marco/Marcos, muito comum no Brasil desde meados do século XX." },
  { name: "Marcos",    origin: "Latina",    meaning: "Consagrado a Marte, o guerreiro",          curiosity: "Nome de um dos quatro evangelistas do Novo Testamento, autor do Evangelho de Marcos." },
  { name: "Renato",    origin: "Latina",    meaning: "Aquele que renasceu",                      curiosity: "Deriva do latim 'renatus' (renascido), associado simbolicamente ao batismo cristão." },
  { name: "Cláudio",   origin: "Latina",    meaning: "Aquele que manca, o coxo",                 curiosity: "Nome de uma das mais tradicionais famílias romanas, à qual pertenceram diversos imperadores." },
  { name: "César",     origin: "Latina",    meaning: "Aquele que tem cabelos fartos",            curiosity: "Nome imortalizado por Júlio César, general e estadista romano, tornou-se título imperial." },
  { name: "Alexsandro", origin: "Grega",    meaning: "Aquele que protege os homens",             curiosity: "Variante gráfica popular de Alexandre no Brasil a partir dos anos 1980." },
  { name: "Jonas",     origin: "Hebraica",  meaning: "A pomba, símbolo de paz",                  curiosity: "Nome do profeta bíblico que foi engolido por um grande peixe segundo a narrativa." },
  { name: "Caio",      origin: "Latina",    meaning: "Aquele que se alegra, o feliz",            curiosity: "Um dos praenomen (primeiros nomes) mais comuns na Roma Antiga." },
  { name: "Igor",      origin: "Eslava",    meaning: "O guerreiro protegido pelos deuses",       curiosity: "Nome de origem russa/eslava, ligado a antigos príncipes da Rússia medieval." },
  { name: "Murilo",    origin: "Latina",    meaning: "Aquele que tem paredes fortes, o protegido", curiosity: "Nome bastante popular no Brasil, com uso raro em outros países de língua portuguesa." },
  { name: "Leandro",   origin: "Grega",     meaning: "O homem-leão, forte como um leão",         curiosity: "Nome de uma lenda grega de amor trágico entre Hero e Leandro." },
  { name: "Fábio",     origin: "Latina",    meaning: "Aquele que cultiva favas",                 curiosity: "Nome de uma tradicional família romana (gens Fabia), conhecida por generais e cônsules." },
  { name: "Adriano",   origin: "Latina",    meaning: "Aquele que vem do mar Adriático",          curiosity: "Nome do imperador romano Adriano, conhecido por construir o famoso Muro de Adriano na Britânia." },
  { name: "Douglas",   origin: "Escocesa",  meaning: "Aquele que vem do riacho escuro",          curiosity: "Originalmente um sobrenome escocês/gaélico, tornou-se muito popular como nome próprio no Brasil." },
  { name: "Elton",     origin: "Inglesa",   meaning: "Da vila antiga, da cidade velha",          curiosity: "Nome popularizado internacionalmente pelo cantor britânico Elton John." },
  { name: "Cristiano", origin: "Latina",    meaning: "Seguidor de Cristo, o cristão",            curiosity: "Forma masculina de Cristina, ganhou grande popularidade mundial associado a jogadores de futebol." },
  { name: "Everton",   origin: "Inglesa",   meaning: "Da vila do javali",                        curiosity: "Nome originado do time de futebol inglês Everton FC, tornou-se popular como nome próprio no Brasil." },
  { name: "Jefferson", origin: "Inglesa",   meaning: "Filho de Jeffrey, filho da paz de Deus",   curiosity: "Nome de origem sobrenominal inglesa, popularizado no Brasil em homenagem ao presidente americano Thomas Jefferson." },

  // === Leva 5 - nomes femininos ===
  { name: "Patrícia",  origin: "Latina",    meaning: "Aquela que é nobre, de linhagem nobre",    curiosity: "Feminino de Patrício, título dado à nobreza da Roma Antiga." },
  { name: "Fernanda",  origin: "Germânica", meaning: "Aquela que é corajosa e audaciosa na paz", curiosity: "Forma feminina de Fernando, popular em toda a Península Ibérica e no Brasil." },
  { name: "Juliana",   origin: "Latina",    meaning: "Descendente de Júpiter, a jovem",          curiosity: "Forma alongada de Júlia, muito popular no Brasil entre as décadas de 1970 e 1990." },
  { name: "Camila",    origin: "Etrusca",   meaning: "Aquela que é nobre, isenta de servidão",   curiosity: "Nome de origem etrusca usado na mitologia romana para uma guerreira virgem." },
  { name: "Larissa",   origin: "Grega",     meaning: "A cidadela, aquela que é doce e alegre",   curiosity: "Nome de origem grega ligado a uma antiga cidade da Tessália, na Grécia." },
  { name: "Renata",    origin: "Latina",    meaning: "Aquela que renasceu",                      curiosity: "Forma feminina de Renato, associada simbolicamente ao renascimento espiritual." },
  { name: "Débora",    origin: "Hebraica",  meaning: "A abelha",                                 curiosity: "Nome de uma profetisa e juíza bíblica, uma das poucas líderes mulheres do Antigo Testamento." },
  { name: "Priscila",  origin: "Latina",    meaning: "Aquela que é antiga, venerável",           curiosity: "Nome bíblico de uma das primeiras cristãs mencionadas no Novo Testamento." },
  { name: "Gabriela",  origin: "Hebraica",  meaning: "Deus é minha força",                       curiosity: "Forma feminina de Gabriel, um dos nomes femininos mais populares no Brasil nas décadas de 1990-2000." },
  { name: "Daniela",   origin: "Hebraica",  meaning: "Deus é meu juiz",                          curiosity: "Forma feminina de Daniel, muito comum em diversos países de língua portuguesa e espanhola." },
  { name: "Natália",   origin: "Latina",    meaning: "Aquela que nasceu no dia do Natal",        curiosity: "Deriva do latim 'natalis' (nascimento), tradicionalmente associado ao nascimento de Jesus." },
  { name: "Carolina",  origin: "Germânica", meaning: "Aquela que é livre e forte",               curiosity: "Forma feminina de Carlos, nome de estados americanos (Carolina do Norte e do Sul)." },
  { name: "Bruna",     origin: "Germânica", meaning: "Aquela que tem a pele escura, a morena",   curiosity: "Forma feminina de Bruno, bastante popular no Brasil desde os anos 1990." },
  { name: "Aline",     origin: "Germânica", meaning: "Aquela que é nobre",                       curiosity: "Forma reduzida de Adelina/Adalina, muito popular no Brasil nas décadas de 1980 e 1990." },
  { name: "Michele",   origin: "Hebraica",  meaning: "Quem é como Deus?",                        curiosity: "Forma feminina de Miguel, de origem francesa/italiana, popular em diversos países ocidentais.", aliases: ["Michelle", "Mishele", "Micheli"] },
  { name: "Viviane",   origin: "Latina",    meaning: "Aquela que está viva, cheia de vida",      curiosity: "Nome ligado à lendária Dama do Lago nas histórias arturianas medievais." },
  { name: "Andressa",  origin: "Grega",     meaning: "A viril, a corajosa",                      curiosity: "Forma feminina brasileira de André, com grafia própria diferente da variante 'Andrea'.", aliases: ["Andresa", "Andrezza", "Andreza"] },
  { name: "Franciele", origin: "Latina",    meaning: "A francesa, a mulher livre",               curiosity: "Variante brasileira de Francisca/Francesca, muito popular a partir dos anos 1990.", aliases: ["Francielle", "Francieli", "Fransciele"] },
  { name: "Kelly",     origin: "Irlandesa", meaning: "A guerreira brilhante",                    curiosity: "Nome de origem irlandesa/gaélica, ganhou popularidade internacional a partir dos anos 1970-80.", aliases: ["Keli", "Kely", "Quelly"] },

  // === Leva 5 - nomes clássicos brasileiros adicionais ===
  { name: "Benedito",  origin: "Latina",    meaning: "Aquele que é abençoado",                   curiosity: "Nome ligado a São Bento, muito tradicional em famílias brasileiras, especialmente afrodescendentes." },
  { name: "Custódio",  origin: "Latina",    meaning: "Aquele que guarda, o guardião",            curiosity: "Nome tradicional relacionado à ideia de proteção e guarda, comum em gerações mais antigas." },
  { name: "Anastácia", origin: "Grega",     meaning: "Aquela que ressuscitou",                    curiosity: "Nome ligado à ressurreição na tradição cristã, com forte presença em famílias brasileiras antigas." },
  { name: "Belisário", origin: "Latina",    meaning: "Aquele que atira bem, o certeiro",         curiosity: "Nome de um famoso general do Império Bizantino, conhecido por suas conquistas militares." },
  { name: "Genoveva",  origin: "Germânica", meaning: "Aquela que é da tribo, mulher do povo",    curiosity: "Nome de Santa Genoveva, padroeira de Paris, protetora da cidade contra invasões." },
  { name: "Idalina",   origin: "Germânica", meaning: "Aquela que trabalha, a diligente",         curiosity: "Nome tradicional português, hoje raro, associado a gerações mais antigas de famílias brasileiras." },
  { name: "Leonor",    origin: "Germânica", meaning: "Aquela que é a luz, a compaixão",          curiosity: "Nome usado por diversas rainhas europeias ao longo da história, incluindo rainhas de Portugal." },
  { name: "Filomena",  origin: "Grega",     meaning: "Aquela que é amada, a amiga forte",        curiosity: "Nome de uma santa muito venerada no século XIX, apesar de sua história ser controversa historicamente." },
  { name: "Otacília",  origin: "Latina",    meaning: "Feminino de Otávio, a oitava filha",       curiosity: "Nome tradicional brasileiro, associado a gerações do início e meados do século XX." },
  { name: "Herculano", origin: "Grega",     meaning: "Aquele que tem a glória de Hera, o forte", curiosity: "Nome relacionado ao herói mitológico Hércules, símbolo de força extraordinária." },

  // === Leva 6 - nomes masculinos ===
  { name: "Vicente",   origin: "Latina",    meaning: "Aquele que vence, o vencedor",             curiosity: "Nome ligado a São Vicente, padroeiro de Lisboa e de diversas cidades do mundo lusófono." },
  { name: "Vinicius",  origin: "Latina",    meaning: "Aquele que é ligado ao vinho",             curiosity: "Grafia sem acento de Vinícius, também muito comum em registros brasileiros.", aliases: ["Vinícius", "Vinicius", "Vinicios"] },
  { name: "Nathan",    origin: "Hebraica",  meaning: "Aquele que foi dado, presente de Deus",    curiosity: "Nome do profeta bíblico que confrontou o rei Davi após seu pecado com Bate-Seba." },
  { name: "Joaquim",   origin: "Hebraica",  meaning: "Deus estabelecerá, Deus erguerá",          curiosity: "Nome tradicional ligado ao pai de Maria (mãe de Jesus) na tradição católica." },
  { name: "Salvador",  origin: "Latina",    meaning: "Aquele que salva",                          curiosity: "Nome com forte significado religioso, também dá nome à capital da Bahia." },
  { name: "Domingos",  origin: "Latina",    meaning: "Aquele que pertence ao Senhor",            curiosity: "Nome ligado ao dia do Senhor (domingo) e a São Domingos, fundador da ordem dominicana." },
  { name: "Aurélio",   origin: "Latina",    meaning: "Aquele que é dourado, brilhante",          curiosity: "Nome do imperador filósofo romano Marco Aurélio, autor da obra 'Meditações'." },
  { name: "Ademar",    origin: "Germânica", meaning: "Aquele que é ilustre no combate",          curiosity: "Nome tradicional muito comum entre gerações brasileiras de meados do século XX." },
  { name: "Elton",     origin: "Inglesa",   meaning: "Da vila antiga",                            curiosity: "Nome inglês que ficou popular no Brasil, mesmo sendo pouco usado no Reino Unido atualmente." },
  { name: "Jorge",     origin: "Grega",     meaning: "Aquele que trabalha a terra, o agricultor", curiosity: "Nome de São Jorge, um dos santos guerreiros mais venerados no cristianismo e na cultura afro-brasileira." },
  { name: "Nelson",    origin: "Inglesa",   meaning: "Filho de Neil, filho do campeão",          curiosity: "Popularizado mundialmente por Nelson Mandela, líder histórico da luta contra o apartheid." },
  { name: "Osmar",     origin: "Germânica", meaning: "Aquele que é glorioso como Deus",           curiosity: "Nome de origem germânica bastante comum entre brasileiros nascidos em meados do século XX." },
  { name: "Ivan",      origin: "Russa",     meaning: "Deus é misericordioso, forma eslava de João", curiosity: "Nome usado por diversos czares da Rússia, incluindo Ivan, o Terrível." },
  { name: "Otoniel",   origin: "Hebraica",  meaning: "Deus é minha força",                        curiosity: "Nome do primeiro juiz de Israel mencionado no livro bíblico de Juízes." },
  { name: "Reinaldo",  origin: "Germânica", meaning: "Aquele que governa com sabedoria",          curiosity: "Forma portuguesa de Reginald, nome usado pela nobreza medieval europeia." },
  { name: "Tarcísio",  origin: "Etrusca",   meaning: "Aquele que vem de Tarquínia",              curiosity: "Nome de origem etrusca associado a um jovem mártir da Igreja Católica primitiva." },
  { name: "Norberto",  origin: "Germânica", meaning: "Aquele que brilha como o norte",           curiosity: "Nome ligado a Santo Norberto, fundador da ordem religiosa dos Premonstratenses." },
  { name: "Ubirajara", origin: "Tupi",      meaning: "Senhor da lança, o chefe guerreiro",       curiosity: "Nome de origem tupi, título de um dos livros mais famosos de José de Alencar." },
  { name: "Anísio",    origin: "Grega",     meaning: "Aquele que cumpre, o realizador",          curiosity: "Nome ligado ao educador brasileiro Anísio Teixeira, um dos pioneiros da educação no Brasil." },
  { name: "Genésio",   origin: "Grega",     meaning: "Aquele que dá origem, o gerador",          curiosity: "Nome tradicional relacionado ao conceito de origem e criação, comum em gerações mais antigas." },

  // === Leva 6 - nomes femininos ===
  { name: "Rute",      origin: "Hebraica",  meaning: "A amiga, a companheira fiel",              curiosity: "Nome de uma das protagonistas bíblicas, símbolo de lealdade e devoção familiar." },
  { name: "Noemi",     origin: "Hebraica",  meaning: "Minha doçura, minha delícia",              curiosity: "Nome bíblico da sogra de Rute, figura central do livro de Rute no Antigo Testamento." },
  { name: "Abigail",   origin: "Hebraica",  meaning: "Fonte de alegria para o pai",              curiosity: "Nome de uma das esposas do rei Davi, conhecida por sua sabedoria na Bíblia." },
  { name: "Talita",    origin: "Aramaica",  meaning: "A menina, a jovem",                         curiosity: "Nome que aparece no Novo Testamento na expressão 'Talita cumi' (menina, levanta-te)." },
  { name: "Miriã",     origin: "Hebraica",  meaning: "A rebelde, a que é amada",                  curiosity: "Variante de Míriam, irmã de Moisés e Arão na tradição bíblica." },
  { name: "Míriam",    origin: "Hebraica",  meaning: "A rebelde, a que é amada",                  curiosity: "Forma tradicional de Míriam, considerada uma das primeiras profetisas da Bíblia hebraica." },
  { name: "Suzana",    origin: "Hebraica",  meaning: "O lírio, a flor branca",                    curiosity: "Nome de origem bíblica que remete à flor do lírio, símbolo de pureza." },
  { name: "Verônica",  origin: "Grega",     meaning: "Aquela que traz a verdadeira imagem",       curiosity: "Nome ligado à tradição cristã da mulher que enxugou o rosto de Jesus a caminho do calvário." },
  { name: "Madalena",  origin: "Hebraica",  meaning: "Aquela que é da cidade de Magdala",         curiosity: "Nome de Maria Madalena, uma das figuras femininas mais importantes do Novo Testamento." },
  { name: "Marisa",    origin: "Latina",    meaning: "Combinação de Maria e Luísa, a do mar",     curiosity: "Nome composto/fundido muito popular no Brasil em meados do século XX." },
  { name: "Roseane",   origin: "Latina",    meaning: "A graciosa como uma rosa",                  curiosity: "Combinação de Rosa e Ana, com grafia própria bastante usada no Brasil." },
  { name: "Denise",    origin: "Grega",     meaning: "Consagrada a Dionísio, deus do vinho",      curiosity: "Forma feminina de Dionísio, muito popular na França e depois difundida no Brasil." },
  { name: "Cristiane", origin: "Latina",    meaning: "Seguidora de Cristo, a cristã",             curiosity: "Forma feminina de Cristiano, muito comum entre brasileiras nascidas nos anos 1970-80.", aliases: ["Cristiani", "Kristiane", "Cristianne"] },
  { name: "Josiane",   origin: "Hebraica",  meaning: "Deus aumentará, forma feminina de José",    curiosity: "Combinação moderna de José com o sufixo francês '-iane', popular no Brasil.", aliases: ["Josiani", "Josyane", "Jociane"] },
  { name: "Elisangela", origin: "Hebraica", meaning: "Combinação de Elisa e Ângela",              curiosity: "Nome tipicamente brasileiro, formado pela fusão de dois nomes de origens diferentes.", aliases: ["Elisângela", "Elizangela", "Elizângela"] },
  { name: "Jaqueline", origin: "Hebraica",  meaning: "Aquele que expulsa, forma feminina de Jacó", curiosity: "Forma francesa de Jacqueline, popularizada mundialmente pela ex-primeira-dama americana Jackie Kennedy.", aliases: ["Jacqueline", "Jaqueline", "Jackeline", "Jaquelini"] },
  { name: "Luciana",   origin: "Latina",    meaning: "Aquela que é luminosa, cheia de luz",       curiosity: "Forma feminina de Luciano, derivado do latim 'lux' (luz)." },
  { name: "Graziela",  origin: "Latina",    meaning: "Aquela que tem graça, a graciosa",          curiosity: "Variante brasileira de Graziella/Graça, com forte presença desde os anos 1980-90." },
  { name: "Rosimeire", origin: "Latina",    meaning: "Combinação de Rosa e Meire (Maria)",        curiosity: "Nome tipicamente brasileiro, formado pela fusão criativa de dois nomes populares.", aliases: ["Rosemeire", "Rosimeiri", "Rozimeire"] },
  { name: "Marinalva", origin: "Latina",    meaning: "Combinação de Marina e Alva (branca)",      curiosity: "Nome composto genuinamente brasileiro, comum em regiões do Nordeste do país." },

  // === Leva 6 - nomes indígenas e afro-brasileiros ===
  { name: "Moema",     origin: "Tupi",      meaning: "Aquela que fala mentiras, personagem de Caramuru", curiosity: "Nome criado pelo poeta Santa Rita Durão na obra 'Caramuru', símbolo do amor não correspondido." },
  { name: "Potira",    origin: "Tupi",      meaning: "A flor",                                    curiosity: "Nome de origem tupi que significa simplesmente 'flor', usado em diversas obras literárias brasileiras." },
  { name: "Araci",     origin: "Tupi",      meaning: "A mãe do dia, o nascer do sol",            curiosity: "Nome de origem indígena relacionado à divindade solar na mitologia tupi-guarani." },
  { name: "Ubaldo",    origin: "Germânica", meaning: "Aquele que é audacioso e corajoso",         curiosity: "Nome tradicional de origem germânica, comum em gerações mais antigas no Brasil." },
  { name: "Iemanjá",   origin: "Iorubá",    meaning: "Mãe cujos filhos são os peixes",            curiosity: "Nome da divindade das águas na religião iorubá, uma das mais cultuadas no Brasil através do candomblé." },
  { name: "Oyá",       origin: "Iorubá",    meaning: "Aquela que rasgou, divindade dos ventos",   curiosity: "Nome de uma divindade feminina do panteão iorubá, associada às tempestades e transformações." },
  { name: "Zumbi",     origin: "Bantu",     meaning: "Espírito ancestral guerreiro",              curiosity: "Nome imortalizado por Zumbi dos Palmares, líder do maior quilombo da história do Brasil." },
  { name: "Aiala",     origin: "Iorubá",    meaning: "Aquela que tem força espiritual",           curiosity: "Nome de origem africana com presença crescente entre famílias afro-brasileiras." },
  { name: "Iara",      origin: "Tupi",      meaning: "A senhora das águas",                       curiosity: "Nome da lendária sereia/sedutora das águas na mitologia indígena brasileira." },

  // === Leva 7 - nomes masculinos ===
  { name: "Otoniel",   origin: "Hebraica",  meaning: "Deus é minha força",                        curiosity: "Nome do primeiro juiz de Israel mencionado no livro bíblico de Juízes." },
  { name: "Wesley",    origin: "Inglesa",   meaning: "Do prado ocidental",                         curiosity: "Nome ligado a John Wesley, fundador do movimento metodista no século XVIII." },
  { name: "Robson",    origin: "Inglesa",   meaning: "Filho de Robert, filho da fama brilhante",   curiosity: "Nome de origem sobrenominal inglesa, muito popular no Brasil desde meados do século XX." },
  { name: "Alisson",   origin: "Germânica", meaning: "Filho de Alice, aquele que é nobre",         curiosity: "Variante gráfica popular de Allison, ganhou força no Brasil a partir dos anos 1990.", aliases: ["Allison", "Alison", "Alysson"] },
  { name: "Kauê",      origin: "Tupi",      meaning: "Variante de Cauê, relativo ao sol forte",    curiosity: "Grafia alternativa com 'K', bastante usada em registros civis recentes no Brasil." },
  { name: "Yuri",      origin: "Russa",     meaning: "Forma eslava de Jorge, o agricultor",        curiosity: "Popularizado mundialmente por Yuri Gagarin, primeiro ser humano a viajar ao espaço." },
  { name: "Maicon",    origin: "Inglesa",   meaning: "Variante fonética de Michael",               curiosity: "Grafia adaptada foneticamente ao português, muito comum no Brasil desde os anos 1990.", aliases: ["Michael", "Maikon", "Maycon", "Maikol"] },
  { name: "Deivid",    origin: "Hebraica",  meaning: "Variante gráfica de David, o amado",         curiosity: "Adaptação fonética popular no Brasil para o tradicional nome bíblico David.", aliases: ["David", "Davi", "Deivide", "Deividi"] },
  { name: "Emerson",   origin: "Inglesa",   meaning: "Filho de Emery, filho do trabalho poderoso", curiosity: "Nome sobrenominal inglês, popularizado no Brasil também por associação a pilotos e atletas." },
  { name: "Robério",   origin: "Germânica", meaning: "Aquele que brilha pela fama",                curiosity: "Variante brasileira de Roberto, com uso mais raro e regional." },
  { name: "Wanderley", origin: "Germânica", meaning: "Aquele que vagueia, o caminhante",           curiosity: "Nome de origem germânica adaptado ao português, muito comum entre brasileiros." },
  { name: "Adenilson", origin: "Hebraica",  meaning: "Combinação de Adenil e filho (son)",         curiosity: "Nome tipicamente brasileiro, formado pela fusão criativa de elementos diferentes." },
  { name: "Weverton",  origin: "Inglesa",   meaning: "Variante fonética de Wellington",             curiosity: "Adaptação fonética brasileira popularizada a partir dos anos 1990-2000.", aliases: ["Wellington", "Weberton", "Welington"] },
  { name: "Cleiton",   origin: "Inglesa",   meaning: "Variante fonética de Clayton",                curiosity: "Nome adaptado ao português a partir do inglês Clayton, muito popular no Brasil.", aliases: ["Clayton", "Kleiton", "Cleyton"] },

  // === Leva 7 - nomes femininos ===
  { name: "Ingrid",    origin: "Nórdica",   meaning: "Aquela que é bela como Ing, deusa da fertilidade", curiosity: "Nome escandinavo popularizado mundialmente pela atriz Ingrid Bergman." },
  { name: "Raissa",    origin: "Grega",     meaning: "A mais fácil, a mais leve",                  curiosity: "Nome popularizado no Brasil a partir dos anos 1990, com variações gráficas como Raíssa." },
  { name: "Thainá",    origin: "Tupi",      meaning: "Aquela que é filha da mãe, a filha querida", curiosity: "Nome de origem indígena que se tornou muito popular no Brasil a partir dos anos 2000." },
  { name: "Kimberly",  origin: "Inglesa",   meaning: "Do prado real",                              curiosity: "Nome inglês popularizado mundialmente a partir da cultura pop americana." },
  { name: "Jennifer",  origin: "Galesa",    meaning: "Aquela que tem os cabelos claros e a face bela", curiosity: "Forma inglesa do nome galês Gwenhwyfar (Guinevere), lendária rainha arturiana." },
  { name: "Rayane",    origin: "Árabe",     meaning: "Aquela que tem doçura, aroma agradável",     curiosity: "Nome de origem árabe que ganhou popularidade crescente no Brasil nas últimas décadas.", aliases: ["Rayanne", "Raiane", "Raianne"] },
  { name: "Estefani",  origin: "Grega",     meaning: "A coroada, aquela que usa coroa",            curiosity: "Variante fonética brasileira do tradicional nome grego Stephanie/Estefânia.", aliases: ["Sthefany", "Stephanie", "Stefani", "Estefania", "Stephany"] },
  { name: "Emanuely",  origin: "Hebraica",  meaning: "Deus está conosco",                          curiosity: "Variante gráfica feminina moderna de Emanuel, popular em registros civis recentes.", aliases: ["Emanuely", "Emanueli", "Emanuelly", "Emanuely"] },
  { name: "Ketlyn",    origin: "Irlandesa", meaning: "Variante fonética de Kathleen, a pura",       curiosity: "Adaptação fonética brasileira do nome irlandês Kathleen.", aliases: ["Kathleen", "Katlyn", "Katilene"] },
  { name: "Sarah",     origin: "Hebraica",  meaning: "A princesa, a senhora",                       curiosity: "Nome da esposa do patriarca Abraão, uma das matriarcas mais importantes da Bíblia." },
  { name: "Letícia",   origin: "Latina",    meaning: "Aquela que traz alegria e felicidade",       curiosity: "Deriva do latim 'laetitia' (alegria), muito popular no Brasil desde os anos 1980." },
  { name: "Milena",    origin: "Eslava",    meaning: "Aquela que é graciosa e amada",              curiosity: "Nome de origem eslava já mencionado anteriormente, reforçando presença na base." },
  { name: "Pietra",    origin: "Grega",     meaning: "Forma feminina de Pedro, a pedra",           curiosity: "Variante italiana feminina de Pedro, ganhou popularidade no Brasil a partir dos anos 2010." },

  // === Leva 7 - nomes clássicos e regionais adicionais ===
  { name: "Expedito",  origin: "Latina",    meaning: "Aquele que é rápido, pronto para agir",      curiosity: "Nome ligado a São Expedito, padroeiro das causas urgentes, muito venerado no Brasil." },
  { name: "Deolinda",  origin: "Latina",    meaning: "Bela como Deus a fez",                        curiosity: "Nome tradicional português que remete à beleza divina, comum em gerações antigas." },
  { name: "Firmino",   origin: "Latina",    meaning: "Aquele que é firme, constante",              curiosity: "Nome de origem latina relacionado à firmeza de caráter, comum no interior do Brasil." },
  { name: "Anacleta",  origin: "Grega",     meaning: "Aquela que foi chamada de volta",            curiosity: "Nome tradicional ligado a um dos primeiros papas da Igreja Católica, São Anacleto." },
  { name: "Rosalvo",   origin: "Latina",    meaning: "Combinação de Rosa e Alvo (branco)",         curiosity: "Nome composto genuinamente brasileiro, comum em gerações mais antigas." },
  { name: "Balbina",   origin: "Latina",    meaning: "Aquela que gagueja levemente",               curiosity: "Nome ligado a Santa Balbina, mártir cristã dos primeiros séculos, hoje raro no Brasil." },
  { name: "Hermínio",  origin: "Germânica", meaning: "Aquele que é guerreiro do exército",         curiosity: "Nome de origem germânica ligado a Armínio, líder germânico que derrotou os romanos." },
  { name: "Maura",     origin: "Latina",    meaning: "Aquela que vem da Mauritânia, a morena",     curiosity: "Feminino de Mauro, relacionado à região histórica do norte da África." },
  { name: "Petronilha", origin: "Latina",   meaning: "Feminino de Petrônio, relativa à pedra",      curiosity: "Nome ligado a Santa Petronila, tradicionalmente associada como filha espiritual de São Pedro." },
  { name: "Anacleto",  origin: "Grega",     meaning: "Aquele que foi chamado de volta",            curiosity: "Nome de um dos primeiros papas da história da Igreja Católica, no século I.", aliases: ["Anacletho"] },
  { name: "Shirlei", origin: "Inglesa", meaning: "Prado brilhante, campo claro", curiosity: "Vem do inglês 'Shirley', originalmente um sobrenome que virou nome próprio, popularizado pela atriz Shirley Temple.", aliases: ["Shirley", "Shirleide", "Shirlene"] },
];
